name: scanning-squid
channels: 
 - defaults
 - conda-forge
dependencies:
 - h5py
 - matplotlib=2.0.2
 - pyqtgraph 
 - python=3.6
 - jsonschema
 - pyvisa=1.8.0
 - QtPy
 - sip
 - pyqt=5.6.0
 - numpy=1.13.3
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
 - pint
 - scipy
 - nidaqmx-python
 - jupyterlab
 - pip:
    - qcodes==0.1.11
    - sphinxcontrib-jsonschema
    - nbsphinx
